export const PRODUCT_REQUEST= "PRODUCT_REQUEST";
export const PRODUCT_FAILURE= "PRODUCT_FAILURE";
//post
export const ADD_PRODUCT_SUCCESS= "ADD_PRODUCT_SUCCESS";

//get
export const GET_PRODUCT_SUCCESS= "GET_PRODUCT_SUCCESS";
export const GET_INPROGRESSDATA_SUCCESS= "GET_INPROGRESSDATA_SUCCESS";
export const GET_SOLVEDDATA_SUCCESS= "GET_SOLVEDDATA_SUCCESS";
export const GET_ONHOLDDATA_SUCCESS= "GET_ONHOLDDATA_SUCCESS";
export const GET_QUEUEDATA_SUCCESS= "GET_QUEUEDATA_SUCCESS";
export const GET_STATUSUPDATEDATA_SUCCESS= "GET_STATUSUPDATEDATA_SUCCESS";

//patch
export const PATCH_PRODUCT_SUCCESS= "PATCH_PRODUCT_SUCCESS"
//Delete Product
export const DELETE_PRODUCT_SUCCESS= "DELETE_PRODUCT_SUCCESS"
//
export const    POST_COMMENT_SUCCESS= "POST_COMMENT_SUCCESS"
//
export const    GET_USERSEARCH_SUCCESS= "GET_USERSEARCH_SUCCESS"
//
export const    GET_Categories_SUCCESS= "GET_Categories_SUCCESS"
//
export const    GET_assemblies_SUCCESS= "GET_assemblies_SUCCESS"
//
export const    POST_COMPLAINER_SUCCESS= "POST_COMPLAINER_SUCCESS"
//
export const    POST_COMPLAINTE_SUCCESS= "POST_COMPLAINTE_SUCCESS"
//
export const GET_KARYKARTA_SUCCESS= "GET_KARYKARTA_SUCCESS";
//
export const GET_ADHIKARI_SUCCESS= "GET_ADHIKARI_SUCCESS";


////homepage/////

export const GET_CatTotal_SUCCESS= "GET_CatTotal_SUCCESS";
export const GET_ATTEND_SUCCESS= "GET_ATTEND_SUCCESS";
export const GET_INWARDOUT_SUCCESS= "GET_INWARDOUT_SUCCESS";
export const GET_DEVELOPMENT_SUCCESS= "GET_DEVELOPMENT_SUCCESS";
export const GET_TODAYEVENT_SUCCESS= "GET_TODAYEVENT_SUCCESS";
export const GET_OFFICE_SUCCESS= "GET_OFFICE_SUCCESS";
export const GET_STATUS_SUCCESS= "GET_STATUS_SUCCESS";

////////visitors/////////
export const GET_MASTERVISIT_SUCCESS= "GET_MASTERVISIT_SUCCESS";
export const GET_VISITORS_SUCCESS= "GET_VISITORS_SUCCESS";
export const GET_FILTERVISITORS_SUCCESS= "GET_FILTERVISITORS_SUCCESS";


