export const PRODUCT_REQUEST= "PRODUCT_REQUEST";
export const PRODUCT_FAILURE= "PRODUCT_FAILURE";
//post
export const ADD_PRODUCT_SUCCESS= "ADD_PRODUCT_SUCCESS";

//get
export const GET_PRODUCT_SUCCESS= "GET_PRODUCT_SUCCESS";
export const GET_INPROGRESSDATA_SUCCESS= "GET_INPROGRESSDATA_SUCCESS";
export const GET_SOLVEDDATA_SUCCESS= "GET_SOLVEDDATA_SUCCESS";
export const GET_ONHOLDDATA_SUCCESS= "GET_ONHOLDDATA_SUCCESS";
export const GET_QUEUEDATA_SUCCESS= "GET_QUEUEDATA_SUCCESS";
export const GET_STATUSUPDATEDATA_SUCCESS= "GET_STATUSUPDATEDATA_SUCCESS";

//patch
export const PATCH_PRODUCT_SUCCESS= "PATCH_PRODUCT_SUCCESS"
//Delete Product
export const DELETE_PRODUCT_SUCCESS= "DELETE_PRODUCT_SUCCESS"
//
export const    POST_COMMENT_SUCCESS= "POST_COMMENT_SUCCESS"
//
export const    GET_SEARCH_SUCCESS= "GET_SEARCH_SUCCESS"
//
export const    GET_SEARCH_INPROGRESS_SUCCESS= "GET_SEARCH_INPROGRESS_SUCCESS"
//
export const    GET_SEARCH_SOLVED_SUCCESS= "GET_SEARCH_SOLVED_SUCCESS"
//
export const    GET_SEARCH_ONHOLD_SUCCESS= "GET_SEARCH_ONHOLD_SUCCESS"
//
export const    GET_SEARCH_QUEUE_SUCCESS= "GET_SEARCH_QUEUE_SUCCESS"
//
export const    GET_SEARCH_STATUSUPDATE_SUCCESS= "GET_SEARCH_STATUSUPDATE_SUCCESS"

//Filter/////////
export const    GET_FILTER_SUCCESS= "GET_FILTER_SUCCESS"
//
export const    GET_FILTER_INPROGRESS_SUCCESS= "GET_FILTER_INPROGRESS_SUCCESS"
//
export const    GET_FILTER_SOLVED_SUCCESS= "GET_FILTER_SOLVED_SUCCESS"
//
export const    GET_FILTER_ONHOLD_SUCCESS= "GET_FILTER_ONHOLD_SUCCESS"
//
export const    GET_FILTER_QUEUE_SUCCESS= "GET_FILTER_QUEUE_SUCCESS"
//
export const    GET_FILTER_STATUSUPDATE_SUCCESS= "GET_FILTER_STATUSUPDATE_SUCCESS"



//
export const    GET_USERSEARCH_SUCCESS= "GET_USERSEARCH_SUCCESS"
//
export const    GET_Categories_SUCCESS= "GET_Categories_SUCCESS"
//
export const    GET_assemblies_SUCCESS= "GET_assemblies_SUCCESS"
//
export const    POST_COMPLAINER_SUCCESS= "POST_COMPLAINER_SUCCESS"
//
export const    POST_COMPLAINTE_SUCCESS= "POST_COMPLAINTE_SUCCESS"
//
export const GET_KARYKARTA_SUCCESS= "GET_KARYKARTA_SUCCESS";
//
export const GET_ADHIKARI_SUCCESS= "GET_ADHIKARI_SUCCESS";
export const GET_CatTotal_SUCCESS= "GET_CatTotal_SUCCESS";
